sudo: false

language: groovy
jdk:
  - oraclejdk7
  - oraclejdk8

install: TERM=dumb ./gradlew assemble
script: TERM=dumb ./gradlew check
after_success: TERM=dumb ./gradlew uploadArchives

branches:
  only:
    - master
    - /^stable-.*$/
    - /^issue-.*$/
    - /^pull-.*$/

env:
  global:
    - secure: Jrz3fDLlQYwikFVGOhLzBSYOdcruMrFolt1HQbAr4BnCvxnfafTwRNCXUbfzPmsC1bI38zg9c1uP0jcx7UWt5rEpr52rTXvHBakvt/ErBrB3QMRgwlJNkZe7lSjqlS3uFlk0hzPd5k9n5u9XzadFjUNOTfFy8f12a1fAhnJvURk=
    - secure: LiFvhrq7cDJzinwvLCLHLFvLc+RjQcWWT9q1WO1eGsegkOpT9+GRNLNg4qoaqUdlWYhFJF83lX/+GuZPi0Uz7QBxsdVHY+xYSBv9QxPtj1Rt3oEDBw2dy1SDtaqAcpKvHzCPl10KFcNbOauGD7bCHG1mjwvJzR6oGGFrXUAeV6g=
